---

- name: Prep for OpenShift install 
  hosts: all 
  tasks: 



    - name: update system
      yum:
        name: "*"
        state: latest


    - name: install needed packges 
      yum:
        name:
          - wget
          - git
          - net-tools
          - bind-utils
          - iptables-services
          - bridge-utils
          - bash-completion
          - kexec-tools
#          - sos
          - psacct 
          - docker
          - PyYAML
          - NetworkManager
        state: latest
        
    - name: reset docker config
      command: docker-storage-setup --reset

    - name: deploy new docker-storage-setup file
      copy:
        src: docker-storage-setup
        dest: /etc/sysconfig/docker-storage-setup

    - name: re-run docker storage setup script
      command: docker-storage-setup



    - name: start and enable docker
      service:
        name: docker
        state: started
        enabled: yes


    - name: start and enable NetworkManager
      service:
        name: NetworkManager 
        state: started
        enabled: yes



